export const provinceSeedData = [
  { name: 'Koshi', slug: 'koshi' },
  { name: 'Madhesh', slug: 'madhesh' },
  { name: 'Bagmati', slug: 'bagmati' },
  { name: 'Gandaki', slug: 'gandaki' },
  { name: 'Lumbini', slug: 'lumbini' },
  { name: 'Karnali', slug: 'karnali' },
  { name: 'Sudurpashchim', slug: 'sudurpashchim' },
] as const

export const districtSeedData = [
  { name: 'Bhojpur', slug: 'bhojpur', provinceSlug: 'koshi' },
  { name: 'Dhankuta', slug: 'dhankuta', provinceSlug: 'koshi' },
  { name: 'Ilam', slug: 'ilam', provinceSlug: 'koshi' },
  { name: 'Jhapa', slug: 'jhapa', provinceSlug: 'koshi' },
  { name: 'Khotang', slug: 'khotang', provinceSlug: 'koshi' },
  { name: 'Morang', slug: 'morang', provinceSlug: 'koshi' },
  { name: 'Okhaldhunga', slug: 'okhaldhunga', provinceSlug: 'koshi' },
  { name: 'Panchthar', slug: 'panchthar', provinceSlug: 'koshi' },
  { name: 'Sankhuwasabha', slug: 'sankhuwasabha', provinceSlug: 'koshi' },
  { name: 'Solukhumbu', slug: 'solukhumbu', provinceSlug: 'koshi' },
  { name: 'Sunsari', slug: 'sunsari', provinceSlug: 'koshi' },
  { name: 'Taplejung', slug: 'taplejung', provinceSlug: 'koshi' },
  { name: 'Tehrathum', slug: 'tehrathum', provinceSlug: 'koshi' },
  { name: 'Udayapur', slug: 'udayapur', provinceSlug: 'koshi' },
  { name: 'Bara', slug: 'bara', provinceSlug: 'madhesh' },
  { name: 'Dhanusha', slug: 'dhanusha', provinceSlug: 'madhesh' },
  { name: 'Mahottari', slug: 'mahottari', provinceSlug: 'madhesh' },
  { name: 'Parsa', slug: 'parsa', provinceSlug: 'madhesh' },
  { name: 'Rautahat', slug: 'rautahat', provinceSlug: 'madhesh' },
  { name: 'Saptari', slug: 'saptari', provinceSlug: 'madhesh' },
  { name: 'Sarlahi', slug: 'sarlahi', provinceSlug: 'madhesh' },
  { name: 'Siraha', slug: 'siraha', provinceSlug: 'madhesh' },
  { name: 'Bhaktapur', slug: 'bhaktapur', provinceSlug: 'bagmati' },
  { name: 'Chitwan', slug: 'chitwan', provinceSlug: 'bagmati' },
  { name: 'Dhading', slug: 'dhading', provinceSlug: 'bagmati' },
  { name: 'Dolakha', slug: 'dolakha', provinceSlug: 'bagmati' },
  { name: 'Kathmandu', slug: 'kathmandu', provinceSlug: 'bagmati' },
  { name: 'Kavrepalanchok', slug: 'kavrepalanchok', provinceSlug: 'bagmati' },
  { name: 'Lalitpur', slug: 'lalitpur', provinceSlug: 'bagmati' },
  { name: 'Makwanpur', slug: 'makwanpur', provinceSlug: 'bagmati' },
  { name: 'Nuwakot', slug: 'nuwakot', provinceSlug: 'bagmati' },
  { name: 'Ramechhap', slug: 'ramechhap', provinceSlug: 'bagmati' },
  { name: 'Rasuwa', slug: 'rasuwa', provinceSlug: 'bagmati' },
  { name: 'Sindhuli', slug: 'sindhuli', provinceSlug: 'bagmati' },
  { name: 'Sindhupalchok', slug: 'sindhupalchok', provinceSlug: 'bagmati' },
  { name: 'Baglung', slug: 'baglung', provinceSlug: 'gandaki' },
  { name: 'Gorkha', slug: 'gorkha', provinceSlug: 'gandaki' },
  { name: 'Kaski', slug: 'kaski', provinceSlug: 'gandaki' },
  { name: 'Lamjung', slug: 'lamjung', provinceSlug: 'gandaki' },
  { name: 'Manang', slug: 'manang', provinceSlug: 'gandaki' },
  { name: 'Mustang', slug: 'mustang', provinceSlug: 'gandaki' },
  { name: 'Myagdi', slug: 'myagdi', provinceSlug: 'gandaki' },
  { name: 'Nawalpur', slug: 'nawalpur', provinceSlug: 'gandaki' },
  { name: 'Parbat', slug: 'parbat', provinceSlug: 'gandaki' },
  { name: 'Syangja', slug: 'syangja', provinceSlug: 'gandaki' },
  { name: 'Tanahun', slug: 'tanahun', provinceSlug: 'gandaki' },
  { name: 'Arghakhanchi', slug: 'arghakhanchi', provinceSlug: 'lumbini' },
  { name: 'Banke', slug: 'banke', provinceSlug: 'lumbini' },
  { name: 'Bardiya', slug: 'bardiya', provinceSlug: 'lumbini' },
  { name: 'Dang', slug: 'dang', provinceSlug: 'lumbini' },
  { name: 'Eastern Rukum', slug: 'eastern-rukum', provinceSlug: 'lumbini' },
  { name: 'Gulmi', slug: 'gulmi', provinceSlug: 'lumbini' },
  { name: 'Kapilvastu', slug: 'kapilvastu', provinceSlug: 'lumbini' },
  { name: 'Palpa', slug: 'palpa', provinceSlug: 'lumbini' },
  { name: 'Parasi', slug: 'parasi', provinceSlug: 'lumbini' },
  { name: 'Pyuthan', slug: 'pyuthan', provinceSlug: 'lumbini' },
  { name: 'Rolpa', slug: 'rolpa', provinceSlug: 'lumbini' },
  { name: 'Rupandehi', slug: 'rupandehi', provinceSlug: 'lumbini' },
  { name: 'Dailekh', slug: 'dailekh', provinceSlug: 'karnali' },
  { name: 'Dolpa', slug: 'dolpa', provinceSlug: 'karnali' },
  { name: 'Humla', slug: 'humla', provinceSlug: 'karnali' },
  { name: 'Jajarkot', slug: 'jajarkot', provinceSlug: 'karnali' },
  { name: 'Jumla', slug: 'jumla', provinceSlug: 'karnali' },
  { name: 'Kalikot', slug: 'kalikot', provinceSlug: 'karnali' },
  { name: 'Mugu', slug: 'mugu', provinceSlug: 'karnali' },
  { name: 'Salyan', slug: 'salyan', provinceSlug: 'karnali' },
  { name: 'Surkhet', slug: 'surkhet', provinceSlug: 'karnali' },
  { name: 'Western Rukum', slug: 'western-rukum', provinceSlug: 'karnali' },
  { name: 'Achham', slug: 'achham', provinceSlug: 'sudurpashchim' },
  { name: 'Baitadi', slug: 'baitadi', provinceSlug: 'sudurpashchim' },
  { name: 'Bajhang', slug: 'bajhang', provinceSlug: 'sudurpashchim' },
  { name: 'Bajura', slug: 'bajura', provinceSlug: 'sudurpashchim' },
  { name: 'Dadeldhura', slug: 'dadeldhura', provinceSlug: 'sudurpashchim' },
  { name: 'Darchula', slug: 'darchula', provinceSlug: 'sudurpashchim' },
  { name: 'Doti', slug: 'doti', provinceSlug: 'sudurpashchim' },
  { name: 'Kailali', slug: 'kailali', provinceSlug: 'sudurpashchim' },
  { name: 'Kanchanpur', slug: 'kanchanpur', provinceSlug: 'sudurpashchim' },
] as const

export const destinationCategorySeedData = [
  { title: 'Trekking & Mountaineering', slug: 'trekking-mountaineering' },
  { title: 'Wildlife & Jungle Safaris', slug: 'wildlife-jungle-safaris' },
  { title: 'Culture & Heritage', slug: 'culture-heritage' },
  { title: 'Leisure & Relaxation', slug: 'leisure-relaxation' },
  { title: 'Adventures', slug: 'adventures' },
] as const
